# Generated by Django 4.2.4 on 2023-10-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ders', '0002_alter_eduprogram_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='days',
            field=models.ManyToManyField(to='ders.day'),
        ),
        migrations.AddField(
            model_name='eduprogram',
            name='time_slots',
            field=models.ManyToManyField(to='ders.timeslot'),
        ),
    ]
