# Generated by Django 4.2.4 on 2023-10-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ders', '0003_day_timeslot_eduprogram_days_eduprogram_time_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(choices=[('Pazartesi', 'Pazartesi'), ('Salı', 'Salı'), ('Çarşamba', 'Çarşamba'), ('Perşembe', 'Perşembe'), ('Cuma', 'Cuma'), ('Cumartesi', 'Cumartesi'), ('Pazar', 'Pazar')], max_length=15),
        ),
    ]
