# Generated by Django 4.2.4 on 2023-10-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ders', '0004_alter_day_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(choices=[('Pazartesi, Salı, Perşembe Cuma', 'PazartesiPazartesi, Salı, Perşembe Cuma'), ('Cumartesi, Pazar', 'Cumartesi Pazar')], max_length=50),
        ),
    ]
