# Generated by Django 4.2.4 on 2023-10-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ders', '0005_alter_day_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eduprogram',
            name='date',
        ),
    ]
