# Generated by Django 4.2.4 on 2023-10-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ders', '0006_remove_eduprogram_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(choices=[('Pazartesi, Salı, Perşembe Cuma', 'Pazartesi, Salı, Perşembe Cuma'), ('Cumartesi, Pazar', 'Cumartesi Pazar')], max_length=50),
        ),
    ]
